apiVersion: apps/v1
kind: Deployment
metadata:
  name: insuranceapp-deployment
  labels:
    app: insuranceapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insuranceapp
  template:
    metadata:
      labels:
        app: insuranceapp
    spec:
      containers:
        - name: insuranceapp-container
          image: sravani629/insuranceapp:14
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: insuranceapp-service
spec:
  type: NodePort
  selector:
    app: insuranceapp
  ports:
    - port: 8081
      targetPort: 8081
      node: 31010
